version: '3'
services:
  backend:
    build:
      context: ./bcknd-dashboard
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frntnd-dashboard
      dockerfile: Dockerfile
    ports:
      - 3000:3000